### ISSUE TITLE
Contribute to meta-rockchip.

### ISSUE THREAD

**Issue by DaniilKl** [madisongh/meta-rk3588#4]
Would you like to contribute recipes from this layer to `meta-rockchip`? The recipes are really useful.

**Comment by madisongh** [comment]
At some point, maybe, but it looks to me like the meta-rockchip hosted at yoctoproject.org is more focused on using the upstream/mainline kernel, and Rockchip's meta-rockchip is more focused on development and testing of their chips/boards/drivers/etc., rather than creating a Yocto-friendly BSP layer. Not sure the stuff here would be appropriate in either place.

**Comment by DaniilKl** [comment]
You have recipes for tools and some classes as well which will be useful in Yocto `meta-rockchip`, many people will be happy to use them. Please, consider contribution. Thanks for the response anyway.
